<?php

declare(strict_types=1);

// DRIVERS DATA
$drivers = [
    [
        'name' => 'Lewis Hamilton',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/lewis-hamilton.html',
        'team' => 'Mercedes-AMG Petronas F1 Team',
        'birthYear' => 1985,
        'nationality' => 'Great Britain',
        'wins' => 100,
        'wonThisSeason' => true,
    ],
    [
        'name' => 'Valtteri Bottas',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/valtteri-bottas.html',
        'team' => 'Mercedes-AMG Petronas F1 Team',
        'birthYear' => 1989,
        'nationality' => 'Finland',
        'wins' => 10,
        'wonThisSeason' => true,
    ],
    [
        'name' => 'Max Verstappen',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/max-verstappen.html',
        'team' => 'Red Bull Racing Honda',
        'birthYear' => 1997,
        'nationality' => 'Netherlands',
        'wins' => 17,
        'wonThisSeason' => true,
    ],
    [
        'name' => 'Sergio Perez',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/sergio-perez.html',
        'team' => 'Red Bull Racing Honda',
        'birthYear' => 1990,
        'nationality' => 'Mexico',
        'wins' => 2,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Daniel Ricciardo',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/daniel-ricciardo.html',
        'team' => 'McLaren F1 Team',
        'birthYear' => 1989,
        'nationality' => 'Australia',
        'wins' => 8,
        'wonThisSeason' => true,
    ],
    [
        'name' => 'Lando Norris',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/lando-norris.html',
        'team' => 'McLaren F1 Team',
        'birthYear' => 1999,
        'nationality' => 'Great Britain',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Charles Leclerc',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/charles-leclerc.html',
        'team' => 'Scuderia Ferrari Mission Winnow',
        'birthYear' => 1997,
        'nationality' => 'Monaco',
        'wins' => 2,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Carlos Sainz',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/carlos-sainz.html',
        'team' => 'Scuderia Ferrari Mission Winnow',
        'birthYear' => 1994,
        'nationality' => 'Spain',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Fernando Alonso',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/fernando-alonso.html',
        'team' => 'Alpine F1 Team',
        'birthYear' => 1981,
        'nationality' => 'Spain',
        'wins' => 32,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Esteban Ocon',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/fernando-alonso.html',
        'team' => 'Alpine F1 Team',
        'birthYear' => 1996,
        'nationality' => 'France',
        'wins' => 1,
        'wonThisSeason' => true,
    ],
    [
        'name' => 'Pierre Gasly',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/pierre-gasly.html',
        'team' => 'Scuderia AlphaTauri Honda',
        'birthYear' => 1996,
        'nationality' => 'France',
        'wins' => 1,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Yuki Tsunoda',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/yuki-tsunoda.html',
        'team' => 'Scuderia AlphaTauri Honda',
        'birthYear' => 2000,
        'nationality' => 'Japan',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Sebastian Vettel',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/S/SEBVET01_Sebastian_Vettel/sebvet01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/sebastian-vettel.html',
        'team' => 'Aston Martin Cognizant F1 Team',
        'birthYear' => 1987,
        'nationality' => 'Germany',
        'wins' => 53,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Lance Stroll',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/lance-stroll.html',
        'team' => 'Aston Martin Cognizant F1 Team',
        'birthYear' => 1998,
        'nationality' => 'Canada',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'George Russel',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/george-russell.html',
        'team' => 'Williams Racing',
        'birthYear' => 1998,
        'nationality' => 'Great Britain',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Nicholas Latifi',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/N/NICLAF01_Nicholas_Latifi/niclaf01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/nicholas-latifi.html',
        'team' => 'Williams Racing',
        'birthYear' => 1995,
        'nationality' => 'Canada',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Kimi Räikkönen',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/K/KIMRAI01_Kimi_R%C3%A4ikk%C3%B6nen/kimrai01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/kimi-raikkonen.html',
        'team' => 'Alfa Romeo Racing ORLEN',
        'birthYear' => 1979,
        'nationality' => 'Finland',
        'wins' => 21,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Antonio Giovinazzi',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/A/ANTGIO01_Antonio_Giovinazzi/antgio01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/antonio-giovinazzi.html',
        'team' => 'Alfa Romeo Racing ORLEN',
        'birthYear' => 1993,
        'nationality' => 'Italy',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Mick Schumacher',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/M/MICSCH02_Mick_Schumacher/micsch02.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/mick-schumacher.html',
        'team' => 'Uralkali Haas F1 Team',
        'birthYear' => 1999,
        'nationality' => 'Switzerland',
        'wins' => 0,
        'wonThisSeason' => false,
    ],
    [
        'name' => 'Nikita Mazepin',
        'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/N/NIKMAZ01_Nikita_Mazepin/nikmaz01.png.transform/2col-retina/image.png',
        'website' => 'https://www.formula1.com/en/drivers/nikita-mazepin.html',
        'team' => 'Uralkali Haas F1 Team',
        'birthYear' => 1999,
        'nationality' => 'Russia',
        'wins' => 0,
        'wonThisSeason' => false,
    ],

];


// TEAMS DATA
$teams = [
    [
        'name' => 'Mercedes-AMG Petronas F1 Team',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Mercedes/_jcr_content/logo.img.jpg/1582638425211.jpg',
        'website' => 'https://www.formula1.com/en/teams/Mercedes.html',
        'year' => 1970,
        'championships' => 7,
        'wins' => 112,
        'teamPrincipal' => 'Toto Wolff',
    ],
    [
        'name' => 'Red Bull Racing Honda',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Red-Bull-Racing/_jcr_content/logo.img.jpg/1610719164360.jpg',
        'website' => 'https://www.formula1.com/en/teams/Red-Bull-Racing.html',
        'year' => 1997,
        'championships' => 4,
        'wins' => 72,
        'teamPrincipal' => 'Christian Horner',
    ],
    [
        'name' => 'McLaren F1 Team',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/McLaren/_jcr_content/logo.img.jpg/1515152760829.jpg',
        'website' => 'https://www.formula1.com/en/teams/McLaren.html',
        'year' => 1966,
        'championships' => 8,
        'wins' => 183,
        'teamPrincipal' => 'Andreas Seidl',
    ],
    [
        'name' => 'Scuderia Ferrari Mission Winnow',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Ferrari/_jcr_content/logo.img.jpg/1521797474166.jpg',
        'website' => 'https://www.formula1.com/en/teams/Ferrari.html',
        'year' => 1950,
        'championships' => 16,
        'wins' => 239,
        'teamPrincipal' => 'Mattia Binotto',
    ],
    [
        'name' => 'Alpine F1 Team',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Alpine/_jcr_content/logo.img.jpg/1611246834255.jpg',
        'website' => 'https://www.formula1.com/en/teams/Alpine.html',
        'year' => 1986,
        'championships' => 2,
        'wins' => 21,
        'teamPrincipal' => 'Davide Brivio',
    ],
    [
        'name' => 'Scuderia AlphaTauri Honda',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/AlphaTauri/_jcr_content/logo.img.jpg/1582650557134.jpg',
        'website' => 'https://www.formula1.com/en/teams/AlphaTauri.html',
        'year' => 1985,
        'championships' => 0,
        'wins' => 2,
        'teamPrincipal' => 'Franz Tost',
    ],
    [
        'name' => 'Aston Martin Cognizant F1 Team',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Aston-Martin/_jcr_content/logo.img.png/1610642928926.png',
        'website' => 'https://www.formula1.com/en/teams/Aston-Martin.html',
        'year' => 2018,
        'championships' => 0,
        'wins' => 1,
        'teamPrincipal' => 'Otmar Szafnauer',
    ],
    [
        'name' => 'Williams Racing',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Williams/_jcr_content/logo.img.jpg/1590743731407.jpg',
        'website' => 'https://www.formula1.com/en/teams/Williams.html',
        'year' => 1978,
        'championships' => 9,
        'wins' => 114,
        'teamPrincipal' => 'Jost Capito',
    ],
    [
        'name' => 'Alfa Romeo Racing ORLEN',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Alfa-Romeo-Racing/_jcr_content/logo.img.jpg/1582650603836.jpg',
        'website' => 'https://www.formula1.com/en/teams/Alfa-Romeo-Racing.html',
        'year' => 1993,
        'championships' => 0,
        'wins' => 1,
        'teamPrincipal' => 'Frédéric Vasseur',
    ],
    [
        'name' => 'Uralkali Haas F1 Team',
        'image' => 'https://www.formula1.com/content/fom-website/en/teams/Haas-F1-Team/_jcr_content/logo.img.jpg/1615481143675.jpg',
        'website' => 'https://www.formula1.com/en/teams/Haas-F1-Team.html',
        'year' => 2016,
        'championships' => 0,
        'wins' => 0,
        'teamPrincipal' => 'Guenther Steiner',
    ],
];


$teamsWithWinsThisSeason = [
    'Mercedes-AMG Petronas F1 Team',
    'Red Bull Racing Honda',
    'McLaren F1 Team',
    'Alpine F1 Team'
];

// RACES DATA
$races = [
    ['location' => 'United states', 'date' => '1635033600', 'dateTime' => '2021-10-24 21:00:00', 'circuit' => 'Circuit of The Americas'],
    ['location' => 'Mexico', 'date' => '1636243200', 'dateTime' => '2021-11-07 20:00:00', 'circuit' => 'Autódromo Hermanos Rodríguez'],
    ['location' => 'Brazil', 'date' => '1636848000', 'dateTime' => '2021-11-14 18:00:00', 'circuit' => 'Autódromo José Carlos Pace'],
    ['location' => 'Qatar', 'date' => '1637452800', 'dateTime' => '2021-11-21 15:00:00', 'circuit' => 'Losail International Circuit'],
    ['location' => 'Saudi Arabia', 'date' => '1638662400', 'dateTime' => '2021-12-05 18:30:00', 'circuit' => 'Jeddah Corniche Circuit'],
    ['location' => 'Abu Dhabi', 'date' => '1639267200', 'dateTime' => '2021-12-12 14:00:00', 'circuit' => 'Yas Marina Circuit'],
];
